version: '3.8'

services:
  backend:
    # For local development (build from source)
    build:
      context: ./backend
      dockerfile: Dockerfile
    # For production (use published image)
    # image: markhill97/chat-backend:1.0
    container_name: chat-backend
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/chat_db
    volumes:
      - ./backend:/app

  frontend:
    # For local development (build from source)
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # For production (use published image)
    # image: markhill97/chat-frontend:1.0
    container_name: chat-frontend
    restart: unless-stopped
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
