version: '3.8'

services:
  backend:
    # For local development (build from source)
    build:
      context: ./backend
      dockerfile: Dockerfile
    # For production (use published image)
    # image: markhill97/chat-backend:1.0
    container_name: chat-backend
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    # For local development (build from source)
    build:
      context: ./frontend

      dockerfile: Dockerfile
    # For production (use published image)
    # image: markhill97/chat-app-frontend:latest
    container_name: chat-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend